fail_fast: true
default_stages: [commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
        language_version: python3.11
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: trailing-whitespace
        exclude: ^.*\.(lock)$||^docs\/
      - id: mixed-line-ending
        exclude: ^.*\.(lock)$||^docs\/
      - id: 'no-commit-to-branch'
        args: [--branch, master, --branch, develop]
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        always_run: true
        stages: [commit-msg]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
    -   id: mypy
        files: ^app/.*\.py$
        additional_dependencies:
          - 'pydantic'
          - 'sqlalchemy[mypy]'
        args: [--show-traceback]
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.258
    hooks:
      - id: ruff
        files: ^app/.*\.py$
        args: [--fix, --exit-non-zero-on-fix]
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        files: ^app/.*\.py$
