version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    hostname: postgres
    environment:
      POSTGRES_USER: starterkit
      POSTGRES_PASSWORD: starterkit
      POSTGRES_DB: starterkit
      DEV_MODE: True
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data:cached
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./:/service/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      RDS_URI: 'postgresql://starterkit:starterkit@postgres:5432/starterkit'
      ALLOWED_ORIGINS_REGISTRY: "origin_uris.txt"
    ports:
      - '8000:8000'
    depends_on:
      - "postgres"
    entrypoint: sh -c "./prestart.sh"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
  
volumes:
  postgres:
  pgadmin-data:
