name: pre-commit

on:
  pull_request:
  push:
    branches: [develop]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install mypy black ruff pydantic sqlalchemy
    
    - name: Lint Check
      run: |
        chmod +x ./scripts/lint.sh
        ./scripts/lint.sh
      shell: bash